ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS reference text,
  ADD COLUMN IF NOT EXISTS consent boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS preferred_contact text,
  ADD COLUMN IF NOT EXISTS priority text,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS assigned_user text,
  ADD COLUMN IF NOT EXISTS utm_source text,
  ADD COLUMN IF NOT EXISTS utm_medium text,
  ADD COLUMN IF NOT EXISTS utm_campaign text,
  ADD COLUMN IF NOT EXISTS need_type text,
  ADD COLUMN IF NOT EXISTS installation_type text,
  ADD COLUMN IF NOT EXISTS hood_type text,
  ADD COLUMN IF NOT EXISTS duct_length text,
  ADD COLUMN IF NOT EXISTS soil_level text,
  ADD COLUMN IF NOT EXISTS accessibility text,
  ADD COLUMN IF NOT EXISTS night_intervention boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS schedule_preference text,
  ADD COLUMN IF NOT EXISTS request_type text,
  ADD COLUMN IF NOT EXISTS maintenance_frequency text,
  ADD COLUMN IF NOT EXISTS urgency_level text,
  ADD COLUMN IF NOT EXISTS landing_page text,
  ADD COLUMN IF NOT EXISTS service_source text,
  ADD COLUMN IF NOT EXISTS zone_source text,
  ADD COLUMN IF NOT EXISTS next_action text,
  ADD COLUMN IF NOT EXISTS next_due_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_intervention_at timestamptz,
  ADD COLUMN IF NOT EXISTS duct_present boolean;